env: "local" # local, dev, prod
postgres:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "password"
    dbname: "database"
    sslmode: "disable"

redis:
    host: "localhost"
    user: "default"
    port: 6379
    password: ""
    db: 0
    protocol: "tcp"

http_server:
    address: "localhost:8085"
    timeout: 40h
    idle_timeout: 90h

clients:
    sso:
        address: "localhost:42042"
        timeout: 5s
        retries: 5
        insecure: true

app:
    name: "url-shortener"
    secret: "DgsqOC0GXfWYqZ9Qqm/iTGqRrrd+MdFXhY3UAlnWr8wyXeGfuzBD7A==" # alternatively, store in env as APP_SECRET
    # this app_secret is randomly generated and doesn't mean a thing,
    # so don't be too happy you've found this on a random commit

# has to match that of token_ttl in sso-auth
token_ttl: 1h
